apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-nginx-deploy
  name: sample-nginx-svc
  namespace: sample-nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-nginx-deploy
  type: LoadBalancer
status:
  loadBalancer: {}
